"""实体规范化服务 — 去重与别名解析。"""

from app.core.logging import logger

# NVIDIA 生态核心实体规范名称映射表
# key: 小写别名, value: 规范名称
_CANONICAL_MAP: dict[str, str] = {
    # Companies
    "nvidia": "NVIDIA",
    "nvda": "NVIDIA",
    "nvidia corporation": "NVIDIA",
    "tsmc": "TSMC",
    "taiwan semiconductor": "TSMC",
    "taiwan semiconductor manufacturing": "TSMC",
    "taiwan semiconductor manufacturing company": "TSMC",
    "sk hynix": "SK Hynix",
    "sk하이닉스": "SK Hynix",
    "samsung": "Samsung",
    "samsung electronics": "Samsung",
    "microsoft": "Microsoft",
    "msft": "Microsoft",
    "meta": "Meta",
    "meta platforms": "Meta",
    "facebook": "Meta",
    "google": "Google",
    "alphabet": "Google",
    "googl": "Google",
    "goog": "Google",
    "amazon": "Amazon",
    "aws": "Amazon Web Services",
    "amazon web services": "Amazon Web Services",
    "amzn": "Amazon",
    "vertiv": "Vertiv",
    "vrt": "Vertiv",
    "micron": "Micron Technology",
    "micron technology": "Micron Technology",
    "mu": "Micron Technology",
    "broadcom": "Broadcom",
    "avgo": "Broadcom",
    "amd": "AMD",
    "advanced micro devices": "AMD",
    "intel": "Intel",
    "intc": "Intel",
    "asml": "ASML",
    "applied materials": "Applied Materials",
    "amat": "Applied Materials",
    "lam research": "Lam Research",
    "lrcx": "Lam Research",
    "eaton": "Eaton",
    "eth": "Eaton",
    "supermicro": "Super Micro Computer",
    "super micro": "Super Micro Computer",
    "smci": "Super Micro Computer",
    "dell": "Dell Technologies",
    "dell technologies": "Dell Technologies",
    "hewlett packard": "HPE",
    "hp enterprise": "HPE",
    "hpe": "HPE",
    "oracle": "Oracle",
    "orcl": "Oracle",
    # Products
    "h100": "H100",
    "h200": "H200",
    "a100": "A100",
    "b100": "B100",
    "b200": "B200",
    "gb200": "GB200",
    "grace hopper": "Grace Hopper",
    "grace blackwell": "Grace Blackwell",
    "gh200": "GH200",
    "nvlink": "NVLink",
    "nvswitch": "NVSwitch",
    "dgx": "DGX",
    "hgx": "HGX",
    "mgx": "MGX",
    "jetson": "Jetson",
    "drive": "DRIVE",
    "instinct": "Instinct MI300",
    "mi300": "Instinct MI300",
    "mi300x": "Instinct MI300X",
    "hbm3": "HBM3",
    "hbm3e": "HBM3E",
    "hbm2e": "HBM2E",
    "hbm": "HBM",
    "cowos": "CoWoS",
    "chip on wafer on substrate": "CoWoS",
    # Technologies
    "cuda": "CUDA",
    "tensor core": "Tensor Cores",
    "tensor cores": "Tensor Cores",
    "transformer engine": "Transformer Engine",
    "nccl": "NCCL",
    "tensorrt": "TensorRT",
    "triton": "Triton",
    "fp8": "FP8",
    "bf16": "BF16",
    "nvme": "NVMe",
    "infiniband": "InfiniBand",
    "roce": "RoCE",
    "rdma": "RDMA",
    "ethernet": "Ethernet",
    # Concepts
    "ai training": "AI Training",
    "model training": "AI Training",
    "llm training": "AI Training",
    "inference": "AI Inference",
    "ai inference": "AI Inference",
    "generative ai": "Generative AI",
    "gen ai": "Generative AI",
    "large language model": "Large Language Models",
    "llm": "Large Language Models",
    "llms": "Large Language Models",
    "foundation model": "Foundation Models",
    "data center": "Data Center",
    "hyperscaler": "Hyperscalers",
    "cloud computing": "Cloud Computing",
    # Resources
    "power": "Power Capacity",
    "electricity": "Power Capacity",
    "power consumption": "Power Capacity",
    "data center power": "Power Capacity",
    "packaging capacity": "Advanced Packaging Capacity",
    "advanced packaging": "Advanced Packaging Capacity",
    "wafer capacity": "Wafer Capacity",
    "foundry capacity": "Wafer Capacity",
    "memory bandwidth": "Memory Bandwidth",
    "interconnect bandwidth": "Interconnect Bandwidth",
    "cooling": "Cooling Infrastructure",
    "liquid cooling": "Liquid Cooling",
}

# 实体类型猜测映射（当 LLM 未给出类型时兜底）
_TYPE_HINTS: dict[str, str] = {
    "NVIDIA": "Company",
    "TSMC": "Company",
    "SK Hynix": "Company",
    "Samsung": "Company",
    "Microsoft": "Company",
    "Meta": "Company",
    "Google": "Company",
    "Amazon": "Company",
    "Amazon Web Services": "Company",
    "Vertiv": "Company",
    "Micron Technology": "Company",
    "Broadcom": "Company",
    "AMD": "Company",
    "Intel": "Company",
    "ASML": "Company",
    "Applied Materials": "Company",
    "Lam Research": "Company",
    "Eaton": "Company",
    "Super Micro Computer": "Company",
    "Dell Technologies": "Company",
    "HPE": "Company",
    "Oracle": "Company",
    "H100": "Product",
    "H200": "Product",
    "A100": "Product",
    "B100": "Product",
    "B200": "Product",
    "GB200": "Product",
    "Grace Hopper": "Product",
    "Grace Blackwell": "Product",
    "GH200": "Product",
    "NVLink": "Technology",
    "NVSwitch": "Technology",
    "DGX": "Product",
    "HGX": "Product",
    "MGX": "Product",
    "Instinct MI300": "Product",
    "Instinct MI300X": "Product",
    "HBM": "Technology",
    "HBM3": "Technology",
    "HBM3E": "Technology",
    "HBM2E": "Technology",
    "CoWoS": "Technology",
    "CUDA": "Technology",
    "Tensor Cores": "Technology",
    "Transformer Engine": "Technology",
    "NCCL": "Technology",
    "TensorRT": "Technology",
    "FP8": "Technology",
    "BF16": "Technology",
    "InfiniBand": "Technology",
    "RoCE": "Technology",
    "AI Training": "Concept",
    "AI Inference": "Concept",
    "Generative AI": "Concept",
    "Large Language Models": "Concept",
    "Foundation Models": "Concept",
    "Data Center": "Concept",
    "Hyperscalers": "Concept",
    "Cloud Computing": "Concept",
    "Power Capacity": "Resource",
    "Advanced Packaging Capacity": "Resource",
    "Wafer Capacity": "Resource",
    "Memory Bandwidth": "Resource",
    "Interconnect Bandwidth": "Resource",
    "Cooling Infrastructure": "Resource",
    "Liquid Cooling": "Resource",
}


def normalize_entity_name(raw_name: str) -> str:
    """将原始实体名称规范化为标准形式。

    优先查规范映射表，找不到则返回 Title Case 形式。
    """
    key = raw_name.strip().lower()
    if key in _CANONICAL_MAP:
        canonical = _CANONICAL_MAP[key]
        logger.debug("entity_name_normalized", raw=raw_name, canonical=canonical)
        return canonical
    # 尝试部分匹配（处理前缀如 "NVIDIA's H100"）
    for alias, canonical in _CANONICAL_MAP.items():
        if alias in key:
            return canonical
    return raw_name.strip()


def guess_entity_type(canonical_name: str) -> str:
    """根据规范名称猜测实体类型（兜底用）。"""
    return _TYPE_HINTS.get(canonical_name, "Company")
