# ruff: noqa
"""add quant research tables.

Revision ID: 94805ad5391a
Revises: c4a7e2d9b1f3
Create Date: 2026-09-30 12:09:36.912030
"""

from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "94805ad5391a"
down_revision: Union[str, Sequence[str], None] = "c4a7e2d9b1f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quant_estimate_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column("fiscal_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
        sa.Column("eps_avg", sa.Float(), nullable=True),
        sa.Column("eps_low", sa.Float(), nullable=True),
        sa.Column("eps_high", sa.Float(), nullable=True),
        sa.Column("revenue_avg", sa.Float(), nullable=True),
        sa.Column("ebitda_avg", sa.Float(), nullable=True),
        sa.Column("ebit_avg", sa.Float(), nullable=True),
        sa.Column("n_analysts", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "symbol", "snapshot_date", "fiscal_date", name="uq_quant_estimate"),
    )
    op.create_index("ix_quant_estimate_market_symbol", "quant_estimate_snapshots", ["market", "symbol"], unique=False)
    op.create_index(op.f("ix_quant_estimate_snapshots_id"), "quant_estimate_snapshots", ["id"], unique=False)
    op.create_table(
        "quant_fundamental_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("latest_quarter_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("filing_date", sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
        sa.Column("income_quarters", sa.JSON(), nullable=False),
        sa.Column("cash_quarters", sa.JSON(), nullable=False),
        sa.Column("balance", sa.JSON(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "symbol", name="uq_quant_fundamental"),
    )
    op.create_index(op.f("ix_quant_fundamental_snapshots_id"), "quant_fundamental_snapshots", ["id"], unique=False)
    op.create_index(
        op.f("ix_quant_fundamental_snapshots_symbol"), "quant_fundamental_snapshots", ["symbol"], unique=False
    )
    op.create_table(
        "quant_results",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("sector_key", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("payload_zh", sa.JSON(), nullable=False),
        sa.Column("payload_en", sa.JSON(), nullable=False),
        sa.Column("grades", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "symbol", "as_of", name="uq_quant_result"),
    )
    op.create_index("ix_quant_result_market_symbol", "quant_results", ["market", "symbol"], unique=False)
    op.create_index(op.f("ix_quant_results_as_of"), "quant_results", ["as_of"], unique=False)
    op.create_index(op.f("ix_quant_results_id"), "quant_results", ["id"], unique=False)
    op.create_table(
        "quant_sector_distributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("market", sqlmodel.sql.sqltypes.AutoString(length=8), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("sector_key", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("metric_key", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market", "as_of", "sector_key", "metric_key", name="uq_quant_distribution"),
    )
    op.create_index(op.f("ix_quant_sector_distributions_as_of"), "quant_sector_distributions", ["as_of"], unique=False)
    op.create_index(op.f("ix_quant_sector_distributions_id"), "quant_sector_distributions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f("ix_quant_sector_distributions_id"), table_name="quant_sector_distributions")
    op.drop_index(op.f("ix_quant_sector_distributions_as_of"), table_name="quant_sector_distributions")
    op.drop_table("quant_sector_distributions")
    op.drop_index(op.f("ix_quant_results_id"), table_name="quant_results")
    op.drop_index(op.f("ix_quant_results_as_of"), table_name="quant_results")
    op.drop_index("ix_quant_result_market_symbol", table_name="quant_results")
    op.drop_table("quant_results")
    op.drop_index(op.f("ix_quant_fundamental_snapshots_symbol"), table_name="quant_fundamental_snapshots")
    op.drop_index(op.f("ix_quant_fundamental_snapshots_id"), table_name="quant_fundamental_snapshots")
    op.drop_table("quant_fundamental_snapshots")
    op.drop_index(op.f("ix_quant_estimate_snapshots_id"), table_name="quant_estimate_snapshots")
    op.drop_index("ix_quant_estimate_market_symbol", table_name="quant_estimate_snapshots")
    op.drop_table("quant_estimate_snapshots")
    # ### end Alembic commands ###
