# ruff: noqa
"""add morning_report and device_token tables.

Revision ID: a969cfdb8f18
Revises: 7f27b19b7abd
Create Date: 2026-09-08 00:00:00.000000
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a969cfdb8f18'
down_revision: Union[str, Sequence[str], None] = '7f27b19b7abd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('locale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_token_id'), 'device_token', ['id'], unique=False)
    op.create_index(op.f('ix_device_token_token'), 'device_token', ['token'], unique=True)
    op.create_index(op.f('ix_device_token_user_id'), 'device_token', ['user_id'], unique=False)
    op.create_table('morning_report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market', 'trade_date', name='uq_morning_report_market_date')
    )
    op.create_index(op.f('ix_morning_report_id'), 'morning_report', ['id'], unique=False)
    op.create_index(op.f('ix_morning_report_market'), 'morning_report', ['market'], unique=False)
    op.create_index(op.f('ix_morning_report_trade_date'), 'morning_report', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_morning_report_trade_date'), table_name='morning_report')
    op.drop_index(op.f('ix_morning_report_market'), table_name='morning_report')
    op.drop_index(op.f('ix_morning_report_id'), table_name='morning_report')
    op.drop_table('morning_report')
    op.drop_index(op.f('ix_device_token_user_id'), table_name='device_token')
    op.drop_index(op.f('ix_device_token_token'), table_name='device_token')
    op.drop_index(op.f('ix_device_token_id'), table_name='device_token')
    op.drop_table('device_token')
    # ### end Alembic commands ###
