# ruff: noqa
"""add factor_skills and factor_runs tables.

Revision ID: f8b40f61ef5b
Revises: 8aed45a3c5a5
Create Date: 2026-05-17 08:15:57.568141
"""
from typing import Sequence, Union

import sqlmodel  # noqa: F401
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8b40f61ef5b'
down_revision: Union[str, Sequence[str], None] = '8aed45a3c5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_categories',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('factor_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('start_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('end_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('factor_jsonb', sa.JSON(), nullable=True),
    sa.Column('narrative_jsonb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'user_id', 'symbol', 'start_date', 'end_date', 'freq', name='uq_factor_run')
    )
    op.create_index(op.f('ix_factor_runs_id'), 'factor_runs', ['id'], unique=False)
    op.create_index(op.f('ix_factor_runs_skill_id'), 'factor_runs', ['skill_id'], unique=False)
    op.create_index(op.f('ix_factor_runs_user_id'), 'factor_runs', ['user_id'], unique=False)
    op.create_table('factor_skills',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=80), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('default_symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('default_start_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('default_end_date', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('default_freq', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('snapshot_factor_jsonb', sa.JSON(), nullable=True),
    sa.Column('narrative_jsonb', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('pin_priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_factor_skills_category', 'factor_skills', ['category'], unique=False)
    op.create_index(op.f('ix_factor_skills_id'), 'factor_skills', ['id'], unique=False)
    op.create_index('ix_factor_skills_owner', 'factor_skills', ['owner_id'], unique=False)
    # 注意：ix_factor_skills_owner_id 与 ix_factor_skills_owner 重复，已移除
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_factor_skills_owner', table_name='factor_skills')
    op.drop_index(op.f('ix_factor_skills_id'), table_name='factor_skills')
    op.drop_index('ix_factor_skills_category', table_name='factor_skills')
    op.drop_table('factor_skills')
    op.drop_index(op.f('ix_factor_runs_user_id'), table_name='factor_runs')
    op.drop_index(op.f('ix_factor_runs_skill_id'), table_name='factor_runs')
    op.drop_index(op.f('ix_factor_runs_id'), table_name='factor_runs')
    op.drop_table('factor_runs')
    op.drop_table('factor_categories')
    # ### end Alembic commands ###
