"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from prometheus_client import Counter, Histogram, Gauge
from starlette_prometheus import metrics, PrometheusMiddleware

# Request metrics
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# Database metrics
db_connections = Gauge("db_connections", "Number of active database connections")

# Custom business metrics
orders_processed = Counter("orders_processed_total", "Total number of orders processed")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" | "error"
)


def _safe_get_path_template(self, request):
    """starlette_prometheus 默认实现在遇到 _IncludedRouter 时会因缺少 .path
    属性而崩溃。此补丁在访问 route.path 前先检查 hasattr，避免 500 错误。"""
    from starlette.routing import Match

    for route in request.app.routes:
        try:
            match, _ = route.matches({"type": "http", **request.scope})
            if match == Match.FULL:
                return getattr(route, "path", request.url.path), True
        except Exception:
            continue
    return request.url.path, False


PrometheusMiddleware.get_path_template = _safe_get_path_template


def setup_metrics(app):
    """Set up Prometheus metrics middleware and endpoints."""
    app.add_middleware(PrometheusMiddleware)
    app.add_route("/metrics", metrics)
